services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./output:/usr/share/nginx/html:ro
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
